#-*- mode: org -*-
#+TITLE:     
#+AUTHOR:    
#+EMAIL:     
#+DATE:      
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:nil mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 

########################### Headers #################################

##+LATEX_HEADER: \usepackage[latin1]{inputenc}
##+LATEX_HEADER: \inputencoding{latin1} 
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \usepackage[spanish,activeacute]{babel}
##+LaTeX_CLASS: xelatex-org-article
#+LATEX_HEADER: \usepackage[left=1.5cm,top=2cm,right=1.5cm,bottom=1cm]{geometry}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{anysize}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{multicol}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{appendix}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \hyphenpenalty=10000
#+LATEX_HEADER: \usepackage[nottoc,numbib]{tocbibind}

########################### Portada #################################

#+INCLUDE: "./header.org"

########################### Resumen #################################

#+begin_latex
\section*{Resumen ejecutivo}
#+end_latex



#+begin_latex
\newpage
#+end_latex

########################### Indice ###################################

# TOC
#+BEGIN_LaTeX
\newpage
\tableofcontents
\newpage
#+END_LaTeX

########################### Contenido #################################

* Introducción
El presente informe tiene como objetivo detallar una propuesta de
trabajo para optar al título de Ingeniero Civil en Computación. Este
trabajo consiste en la implementación de un sistema que permita
identificar contenido relevante en la Web y mostrarlo en orden de
importancia, donde ésta es medida de acuerdo a distintos indicadores
obtenidos de las /Redes Sociales Online/.\\

Este contenido, a diferencia de gran parte del trabajo existente, no
se limitará solamente texto, sino que de modo general puede ser cualquier
tipo de objetos multimedia, como imágenes, videos, sonidos, texto,
etc. Por otra parte, el sistema a implementar será lo más flexible
posible tal que no dependa de las fuentes de contenido que existen hoy
en día en la Web, dada su obsolescencia y corta duración.

Se utilizarán dos tipos de documentos para la experimentación y
evaluación del sistema: noticias y conciertos musicales. Tanto las
noticias como la información de los conciertos serán obtenidos de dos
fuentes ricas en datos de este tipo: Google News[fn:1] y
Last.fm[fn:2]. Para obtener más documentos relacionados a éstos, se
utilizará la red social Twitter[fn:3] tanto como para obtenerlos como
para validar su importancia respecto a los usuarios y a los mensajes
que los mencionan. En la sección Descripción General de la Propuesta
se detalla la forma de utilizar estas fuentes para obtener los datos y
los resultados.\\



** Motivación

Hoy en día la cantidad de datos producidos en la Web 

** Trabajo relacionado

* Descripción del Problema
* Descripción General de la propuesta
* Objetivos
** Objetivo General
** Objetivos Específicos

* Metodología de trabajo
* Plan de trabajo


########################### Referencias #################################

#+INCLUDE: "./footer.org"
